export const Members: {
  [P in string]: { name: string; imageName: string; season: PleyerResult };
} = {
  "11": {
    name: "ダルビッシュ有",
    imageName: "11.png",
    season: {
      isPitcher: true,
      isMajor: true,
      joined: "パドレス",
      era: 3.1,
      win: 16,
      lose: 8,
      hold: 0,
      holdPoint: 0,
      save: 0,
    },
  },
  "12": {
    name: "戸郷翔征",
    imageName: "12.png",
    season: {
      isPitcher: true,
      isMajor: false,
      joined: "巨人",
      era: 2.62,
      win: 12,
      lose: 8,
      hold: 0,
      holdPoint: 0,
      save: 0,
    },
  },
  "13": {
    name: "松井裕樹",
    imageName: "13.png",
    season: {
      isPitcher: true,
      isMajor: false,
      joined: "楽天",
      era: 1.92,
      win: 1,
      lose: 3,
      hold: 7,
      holdPoint: 8,
      save: 32,
    },
  },
  "14": {
    name: "佐々木朗希",
    imageName: "14.png",
    season: {
      isPitcher: true,
      isMajor: false,
      joined: "ロッテ",
      era: 2.02,
      win: 9,
      lose: 4,
      hold: 0,
      holdPoint: 0,
      save: 0,
    },
  },
  "15": {
    name: "大勢",
    imageName: "15.png",
    season: {
      isPitcher: true,
      isMajor: false,
      joined: "巨人",
      era: 2.05,
      win: 1,
      lose: 3,
      hold: 8,
      holdPoint: 9,
      save: 37,
    },
  },
  "16": {
    name: "大谷翔平",
    imageName: "16.png",
    season: {
      isPitcher: false,
      isMajor: true,
      joined: "エンゼルス",
      ba: 0.267,
      homerun: 34,
      rbi: 95,
      steal: 11,
    },
  },
  "17": {
    name: "伊藤大海",
    imageName: "17.png",
    season: {
      isPitcher: true,
      isMajor: false,
      joined: "日ハム",
      era: 2.95,
      win: 10,
      lose: 9,
      hold: 1,
      holdPoint: 1,
      save: 1,
    },
  },
  "18": {
    name: "山本由伸",
    imageName: "18.png",
    season: {
      isPitcher: true,
      isMajor: false,
      joined: "オリックス",
      era: 1.68,
      win: 15,
      lose: 5,
      hold: 0,
      holdPoint: 0,
      save: 0,
    },
  },
  "20": {
    name: "栗林良吏",
    imageName: "20.png",
    season: {
      isPitcher: true,
      isMajor: false,
      joined: "広島",
      era: 1.49,
      win: 0,
      lose: 2,
      hold: 6,
      holdPoint: 6,
      save: 31,
    },
  },
  "21": {
    name: "今永昇太",
    imageName: "21.png",
    season: {
      isPitcher: true,
      isMajor: false,
      joined: "DeNA",
      era: 2.26,
      win: 11,
      lose: 4,
      hold: 0,
      holdPoint: 0,
      save: 0,
    },
  },
  "22": {
    name: "湯浅京己",
    imageName: "22.png",
    season: {
      isPitcher: true,
      isMajor: false,
      joined: "阪神",
      era: 1.09,
      win: 2,
      lose: 3,
      hold: 43,
      holdPoint: 45,
      save: 0,
    },
  },
  "26": {
    name: "宇田川優希",
    imageName: "26.png",
    season: {
      isPitcher: true,
      isMajor: false,
      joined: "オリックス",
      era: 0.81,
      win: 2,
      lose: 1,
      hold: 3,
      holdPoint: 5,
      save: 0,
    },
  },
  "28": {
    name: "高橋宏斗",
    imageName: "28.png",
    season: {
      isPitcher: true,
      isMajor: false,
      joined: "中日",
      era: 2.47,
      win: 6,
      lose: 4,
      hold: 0,
      holdPoint: 0,
      save: 0,
    },
  },
  "29": {
    name: "宮城大弥",
    imageName: "29.png",
    season: {
      isPitcher: true,
      isMajor: false,
      joined: "オリックス",
      era: 3.16,
      win: 11,
      lose: 8,
      hold: 0,
      holdPoint: 0,
      save: 0,
    },
  },
  "47": {
    name: "高橋奎二",
    imageName: "47.png",
    season: {
      isPitcher: true,
      isMajor: false,
      joined: "ヤクルト",
      era: 2.63,
      win: 8,
      lose: 2,
      hold: 0,
      holdPoint: 0,
      save: 0,
    },
  },
  "10": {
    name: "甲斐拓也",
    imageName: "10.png",
    season: {
      isPitcher: false,
      isMajor: false,
      joined: "ソフトバンク",
      ba: 0.18,
      homerun: 1,
      rbi: 27,
      steal: 1,
    },
  },
  "24": {
    name: "大城卓三",
    imageName: "24.png",
    season: {
      isPitcher: false,
      isMajor: false,
      joined: "巨人",
      ba: 0.266,
      homerun: 13,
      rbi: 24,
      steal: 1,
    },
  },
  "27": {
    name: "中村悠平",
    imageName: "27.png",
    season: {
      isPitcher: false,
      isMajor: false,
      joined: "ヤクルト",
      ba: 0.263,
      homerun: 5,
      rbi: 28,
      steal: 0,
    },
  },
  "1": {
    name: "山田哲人",
    imageName: "1.png",
    season: {
      isPitcher: false,
      isMajor: false,
      joined: "ヤクルト",
      ba: 0.243,
      homerun: 23,
      rbi: 65,
      steal: 10,
    },
  },
  "2": {
    name: "源田壮亮",
    imageName: "2.png",
    season: {
      isPitcher: false,
      isMajor: false,
      joined: "西武",
      ba: 0.266,
      homerun: 2,
      rbi: 17,
      steal: 12,
    },
  },
  "3": {
    name: "牧秀悟",
    imageName: "3.png",
    season: {
      isPitcher: false,
      isMajor: false,
      joined: "DeNA",
      ba: 0.291,
      homerun: 24,
      rbi: 87,
      steal: 3,
    },
  },
  "7": {
    name: "中野拓夢",
    imageName: "7.png",
    season: {
      isPitcher: false,
      isMajor: false,
      joined: "阪神",
      ba: 0.276,
      homerun: 6,
      rbi: 25,
      steal: 23,
    },
  },
  "25": {
    name: "岡本和真",
    imageName: "25.png",
    season: {
      isPitcher: false,
      isMajor: false,
      joined: "巨人",
      ba: 0.252,
      homerun: 30,
      rbi: 82,
      steal: 1,
    },
  },
  "33": {
    name: "山川穂高",
    imageName: "33.png",
    season: {
      isPitcher: false,
      isMajor: false,
      joined: "西武",
      ba: 0.266,
      homerun: 41,
      rbi: 90,
      steal: 0,
    },
  },
  "55": {
    name: "村上宗隆",
    imageName: "55.png",
    season: {
      isPitcher: false,
      isMajor: false,
      joined: "ヤクルト",
      ba: 0.318,
      homerun: 55,
      rbi: 134,
      steal: 12,
    },
  },
  "8": {
    name: "近藤健介",
    imageName: "8.png",
    season: {
      isPitcher: false,
      isMajor: false,
      joined: "日ハム",
      ba: 0.302,
      homerun: 8,
      rbi: 51,
      steal: 8,
    },
  },
  "9": {
    name: "周東佑京",
    imageName: "9.png",
    season: {
      isPitcher: false,
      isMajor: false,
      joined: "ソフトバンク",
      ba: 0.267,
      homerun: 5,
      rbi: 15,
      steal: 22,
    },
  },
  "23": {
    name: "ラーズ・ヌートバー",
    imageName: "",
    season: {
      isPitcher: false,
      isMajor: false,
      joined: "カージナルス",
      ba: 0.228,
      homerun: 14,
      rbi: 40,
      steal: 4,
    },
  },
  "34": {
    name: "吉田正尚",
    imageName: "",
    season: {
      isPitcher: false,
      isMajor: false,
      joined: "オリックス",
      ba: 0.335,
      homerun: 21,
      rbi: 88,
      steal: 4,
    },
  },
  "51": {
    name: "鈴木誠也",
    imageName: "34.png",
    season: {
      isPitcher: false,
      isMajor: true,
      joined: "カブス",
      ba: 0.262,
      homerun: 14,
      rbi: 46,
      steal: 9,
    },
  },
  "63": {
    name: "山崎颯一郎",
    imageName: "63.png",
    season: {
      isPitcher: true,
      isMajor: false,
      joined: "オリックス",
      era: 3.0,
      win: 0,
      lose: 2,
      hold: 6,
      holdPoint: 6,
      save: 1,
    },
  },
  "5": {
    name: "牧原大成",
    imageName: "5.png",
    season: {
      isPitcher: false,
      isMajor: false,
      joined: "ソフトバンク",
      ba: 0.301,
      homerun: 6,
      rbi: 42,
      steal: 13,
    },
  },
};

export type PleyerResult = PitchingResult | BattingResult;

interface SeasonResult {
  isPitcher: boolean;
  isMajor: boolean;
  joined: string;
}

interface PitchingResult extends SeasonResult {
  isPitcher: true;
  era: number;
  win: number;
  lose: number;
  hold: number;
  holdPoint: number;
  save: number;
}
interface BattingResult extends SeasonResult {
  isPitcher: false;
  ba: number;
  homerun: number;
  rbi: number;
  steal: number;
}
